### ISSUE TITLE
Vídeos que podamos usar

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/ImpresorasyEscaneo3DTE#1]
Vídeos para poner de fondo
- [Haciendo una máscara de Batman](https://www.youtube.com/watch?v=9EnPe_fBV3E)
- [Muchas cosas](https://www.youtube.com/watch?v=B2Jh6qQ4F10)
- [Perro con prótesis impresas](https://www.youtube.com/watch?v=uRmoowIN8aY)
- [Imprimiendo una estructura](https://www.youtube.com/watch?v=VwXmgMDEiuQ)
- [Niño con mano impresa](https://www.youtube.com/watch?v=CQKcEhTd-Ck)
- [Imprimiendo una casa](https://www.youtube.com/watch?v=gMMsfVBaaDc)
- [Empresa China que imprime casas](https://www.youtube.com/watch?v=OYqBxEAtXZA)

**Comment by iblancasa** [comment]
La spin-off de la UGR, AgeO, tiene varios vídeos de trabajos que han hecho.
Los mejores, a mi gusto, son estos:
- [Columna de Linares](https://www.youtube.com/watch?v=cBwBIvXfnKw)
- [Mena](https://www.youtube.com/watch?v=fGUJRNlxKC8)

El primero lo bueno que tiene es que muestra cómo trabajan

**Comment by JCristobal** [comment]
siento no haberte contestado antes, ya me ha vuelto el internet =S

son todos muy buenos ... el de batman y la empresa china que imprime casas se pueden poner ... y los 2 de las prótesis fijo

**Comment by iblancasa** [comment]
A ver si encontramos más que molen y ya vemos cuales poner exactamente :)
